export type {
  Project,
  ProjectCaseStudy,
  ProjectCategory,
  ProjectContributor,
  ProjectCategoryFilter,
  ProjectDomain,
  ProjectDomainFilter,
  ProjectExplorerState,
  ProjectLink,
  ProjectLinkType,
  ProjectLocalizedContent,
  ProjectMedia,
  ProjectMediaRole,
  ProjectMediaType,
  ProjectResult,
  ProjectSEO,
  ProjectStatus,
  ProjectTechnology,
  ProjectType,
  ProjectViewMode,
  SupportedLocale,
} from "@/features/projects/domain/project.types";

export {
  projectDomains,
  projectStatuses,
  projectTypes,
  supportedLocales,
} from "@/features/projects/domain/project.types";
